@authToken= Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJTYW50YVNlY3JldCBBUEkiLCJzdWIiOiJjZXNhci5zYW50b3MyMDQyQGdtYWlsLmNvbSIsImV4cCI6MTcyMzcwMTMyOX0.2kudfWct2F7X9yl32iA_ZF_fbsRsZkZUo-nE8_NwJws

### Login
POST http://localhost:8080/login HTTP/1.1
content-type: application/json

{
    "email": "cesar.santos2042@gmail.com",
    "password": "12345678"
}

### get user
GET http://localhost:8080/user
Authorization: {{authToken}}


### Save user
POST http://localhost:8080/users HTTP/1.1
content-type: application/json
Authorization: {{authToken}}

{
    "name": "Cesar Santos",
    "email": "cesarf22raptor@gmail.com",
    "password": "l0b1nh042"
}

### Create party
POST http://localhost:8080/party HTTP/1.1
content-Type: application/json
Authorization: {{authToken}}

{
    "name": "",
    "partyDate": "2024-12-25",
    "maxPriceGift": 100.00
}

### Insert unser in a party
POST http://localhost:8080/party/1/user/1 HTTP/1.1
content-Type: application/json
Authorization: {{authToken}}

### Insert unser in a party
POST http://localhost:8080/party/1/user/2 HTTP/1.1
content-Type: application/json
Authorization: {{authToken}}


### Insert unser in a party
POST http://localhost:8080/party/1/user/3 HTTP/1.1
content-Type: application/json
Authorization: {{authToken}}


### Insert unser in a party
POST http://localhost:8080/party/1/user/4 HTTP/1.1
content-Type: application/json
Authorization: {{authToken}}

### Insert unser in a party
POST http://localhost:8080/party/1/user/5 HTTP/1.1
content-Type: application/json
Authorization: {{authToken}}

### Insert user gift in a party
POST http://localhost:8080/party/1/gift HTTP/1.1
content-Type: application/json
Authorization: {{authToken}}

{
    "name": "keyboard",
    "price": 60.00,
    "userId": 1
}

### Insert user gift in a party
POST http://localhost:8080/party/1/gift HTTP/1.1
content-Type: application/json
Authorization: {{authToken}}

{
    "name": "mouse",
    "price": 60.00,
    "userId": 2
}


### Insert user gift in a party
POST http://localhost:8080/party/1/gift HTTP/1.1
content-Type: application/json
Authorization: {{authToken}}

{
    "name": "cpu",
    "price": 60.00,
    "userId": 3
}


### Insert user gift in a party
POST http://localhost:8080/party/1/gift HTTP/1.1
content-Type: application/json
Authorization: {{authToken}}

{
    "name": "mother board",
    "price": 60.00,
    "userId": 4
}


### Insert user gift in a party
POST http://localhost:8080/party/1/gift HTTP/1.1
content-Type: application/json
Authorization: {{authToken}}

{
    "name": "headset",
    "price": 60.00,
    "userId": 5
}


### Get party
GET http://localhost:8080/party/1
Authorization: {{authToken}}

### Generate Secret Santa
POST http://localhost:8080/party/1/generate-scret-santa HTTP/1.1
# content-Type: application/json
Authorization: {{authToken}}
